### ISSUE TITLE
Specified color rules?

### ISSUE THREAD

**Issue by kormyen** [hundredrabbits/Themes#15]
I'm having trouble implementing a single set of css rules that work for all the themes.
The problem is mostly because I am stubbornly trying to have different colors specified for 'menu foreground/background' vs 'content foreground/background' while having (ideally) the same ascent colors between foreground and background.

I propose color rules such as:
1. main background
2. primary high
3. primary medium
4. primary background
5. primary ascent
6. secondary high
7. secondary medium
8. secondary background
9. secondary ascent

RULE: 'x high' AND 'x medium' should be visible/readable on top of 'x background'

Entirely open to opinion/improvement/disagreement obviously.

Rules are made to be broken, but I think breaking them should be deliberate acts. Currently there doesn't seem to be a consistent use of the colors in the themes... but I also could just be using them wrong :D

**Comment by neauoire** [comment]
I added a theme tester. 
Give it a try, tell me after if you're still having issues.

<img width="462" alt="screen shot 2018-09-15 at 6 53 22 am" src="https://user-images.githubusercontent.com/1455726/45569621-2473e800-b8b4-11e8-81a7-6df3388b0fed.png">

<img width="472" alt="screen shot 2018-09-15 at 6 53 28 am" src="https://user-images.githubusercontent.com/1455726/45569629-2dfd5000-b8b4-11e8-82f4-735cdb077e74.png">

**Comment by neauoire** [comment]
I think the problem is that a lot of the themes are crap, and will have to be improved.
I recommend testing with `apollo`, it's one of the better themes.

**Comment by kormyen** [comment]
Thanks for this, they are looking great :D
