### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by pacocoursey** [hundredrabbits/Themes#16]
I'm a big supporter of exposing the `theme.js` file to support these themes being implemented in other web applications. To facilitate this, I think an `npm` package should be published for easier installation and version management.

I know you're mostly against external dependencies in your projects, but I think this would be a worthy pursuit. I'm happy to publish an example package to give an example of how it would work.

Electron application example:

```bash
$ npm install hr-themes         # install the package
```

```js
// renderer.js
const Theme = require('hr-themes');
const theme = new Theme();
theme.install(document.body);
theme.start();
```

This means you can publish changes to the theme code and they will be reflected in every package that has these as a dependency (Left, Dotgrid, Tape...)

You could even include the theme files in the npm package. Then every theme would automatically be accessible from your application. For example:
```js
const Theme = require('hr-themes');
const theme = new Theme();
theme.apply('lotus');    // something like this...
```

**Comment by neauoire** [comment]
I've never done it before but I think this would be nice.
I'll see if I can do this later today :)

**Comment by 2xAA** [comment]
@neauoire Are there still plans to publish to npm?

If that's not possible, would you accept a PR adding a package.json so this can be installed from GitHub using npm or yarn?

**Comment by neauoire** [comment]
I haven't taken the time to look into npm yet, but if you want to do it, go ahead, I will merge it :)
