### ISSUE TITLE
this is not an issue, maybe a waste of time

### ISSUE THREAD

**Issue by joniv2** [hundredrabbits/Themes#57]
i love your guys' work, but i've always wondered what you used in your screenshots. as far as i've seen from your setup, you seem to be using elemetary os in your macbook which cannnot have windows without titlebars. what is the os in the showcase screenshot?
what window manager?

can't wait to hear the response, cheers!

**Comment by rekkabell** [comment]
That particular screenshot was from Devine's machine, running Manjaro with i3 wm.

**Comment by joniv2** [comment]
is the config available somewhere? also thanks for the quick reply!

**Comment by rekkabell** [comment]
Not sure, everything Dev has online would be here: https://wiki.xxiivv.com/site/computer.html

In the future, for questions like this, better to contact us by email or via Mastodon, info here: https://100r.co/site/about_us.html#rabbits

**Comment by neauoire** [comment]
Hey @joniv2

**Comment by rekkabell** [comment]
Oh woops my bad... i looked too quickly, the applications in the themes page screenshot is very old. It has rounded corners.... they were taken when Dev was still on MacOs. The applications themselves were ours and were all made without title bars. The newer screenshots (square corners) tho are all viewed on Plan9 or Manjaro ie community edition, i3 doesn't have title bars.  Sorry for the confusion. We ought to replace that screenshot ;).

**Comment by joniv2** [comment]
the rounded corner ones were my interests, anyways thanks for the reply also sorry for not being clear.
